### ISSUE TITLE
🐞 - `InputChip` issues

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#12161]
### Reproduction url

https://taiga-ui.dev/components/input-chip

### Description

Not sure if the new `InputChip` is still WIP but the demo seems to have some issues.
- "Plain strings" focused input looks like this:

<img width="412" height="95" alt="Image" src="https://github.com/user-attachments/assets/6157601a-2629-4cbd-8909-0aa2400cdbcb" />

- There doesn't seem to be any meaningful separation/padding/margin between the tags and the input. Input cursor seems to be almost touching the tags. The old tag input doesn't have this issue (old: 9px from the cursor to the tag, new: 2px from the top of the cursor to the tag).

<img width="412" height="169" alt="Image" src="https://github.com/user-attachments/assets/5986eb9e-20ee-494b-bbeb-14865389fcee" />

- Filter input in the virtual scroll example doesn't seem to do anything

### Taiga UI version

4.57.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by waterplea** [comment]
First issue is this:
https://github.com/taiga-family/taiga-ui/issues/11889
Left side change is intentional.

Second issue is a bug, input should have height the same as chips.

Third one was added from this blitz:
https://stackblitz.com/edit/angular-cxuffoxm
@splincode I guess the example does not work because of old non-signal ViewChild. Let's hide it in v4, in v5 it would work properly.

**Comment by hakimio** [comment]
> Left side change is intentional.

If you mean the lack of padding and letters touching the border by "the left side change", then it, honestly, looks terrible and is a really poor design decision.

**Comment by waterplea** [comment]
It looks much more reasonable with chips for them to disappear into the end of the container than into some random space:

<img width="353" height="78" alt="Image" src="https://github.com/user-attachments/assets/38c5f877-de32-44a1-9849-443a8495c571" />

<img width="365" height="78" alt="Image" src="https://github.com/user-attachments/assets/07509b75-82a8-445c-8831-a9670ab063e6" />

If you really hate it, you can add `clip-path: inset(0)` to `tui-textfield[multi] .t-items`. The internal DOM structure is as shallow as we could make it, but admittedly that's still a hack.

On a sidenote: horizontal scroll mode is really the last resort, it's much harder on a user than growing height:
- It provides much smaller "slice" of data
- It is harder to scroll with a mouse

**Comment by hakimio** [comment]
> It looks much more reasonable with chips for them to disappear into the end of the container than into some random space

Issue here is that you also have inconsistent padding: large padding on the right and no padding on the left, but, yeah, it might actually make sense in this case.

> On a sidenote: horizontal scroll mode is really the last resort, it's much harder on a user than growing height

Yes, I agree and I use the growing height mode in my app. The issue is mostly with the demo. My suggestion would be to simply remove the ugly and buggy first "Plain strings" demo.

**Comment by waterplea** [comment]
The rest of issues are fixed in v5

**Comment by hakimio** [comment]
The "Plain Strings" single line demo is still not scrollable.

**Comment by waterplea** [comment]
> The "Plain Strings" single line demo is still not scrollable.

What do you mean by «not scrollable»? That's how it behaves for me, same in desktop:

https://github.com/user-attachments/assets/762edcd6-2653-440f-a6f1-cc7661018fdb

**Comment by hakimio** [comment]
I mean there is no way to manually scroll the list with a scrollbar.
Anyway, maybe that's intentional. If it is, that's just strange design.
